// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoxavdhjmcgkkueqbuco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVveGF2ZGhqbWNna2t1ZXFidWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDM5OTYsImV4cCI6MjA3MjgxOTk5Nn0.9HaSPYmW1QP62-_xQ6A8TcFzleOMqTikw4X76p2JJUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});